eureka:
    client:
        service-url:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: ${HOSTNAME:localhost}

server:
    port: 8081

spring:
    application:
        name: ms-catalogue-books
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/anaamaya_books_catalogue?createDatabaseIfNotExist=true
        username: root
    jpa:
        show-sql: true
